### ISSUE TITLE
Hardcoded path in vue3-gettext causing module not found error

### ISSUE THREAD

**Issue by phamhanh** [jshmrtn/vue3-gettext#62] opened 2024-12-17 13:37 UTC
### Description

   I'm encountering a "MODULE_NOT_FOUND" error when running `vue-gettext-extract` due to a hardcoded path in the `vue3-gettext` package.

   ### Steps to Reproduce

   1. Install `vue3-gettext` in a project.
   2. Run the `vue-gettext-extract` command.
   3. Observe the error message.

   ### Error Message
Error: Cannot find module '/home/leo/projects/vue3-gettext/node_modules/tslib/tslib.es6.js'

   ### Expected Behavior

   The `vue-gettext-extract` command should run without errors.

   ### Environment

   - Node.js version: v23.1.0
   - npm version: 9.0.0
   - Operating System: macOS Ventura

   ### Additional Information

   The issue seems to be caused by a hardcoded path in `vue3-gettext/dist/bin/gettext_extract.js`:
javascript
var tslib_es6_js = require('/home/leo/projects/vue3-gettext/node_modules/tslib/tslib.es6.js');
   This path should be relative or dynamically resolved to avoid such errors.

**Comment by lzurbriggen** [comment] 2024-12-17 13:44
Duplicate of #58

@phamhanh Sorry, the `latest` npm tag you probably installes points to quite an old release since we've been on pre-release versions forever now. Please try `4.0.0-alpha.8` or `3.0.0-beta.6`.

**Closed by lzurbriggen** 2024-12-17 13:44 UTC
