### ISSUE TITLE
Cannot extract messages from code

### ISSUE THREAD

**Issue by huynamboz** [jshmrtn/vue3-gettext#59] opened 2024-06-26 10:23 UTC
i'm using window 11, pnpm and my current vue3-gettext's version is `3.0.0-beta.6` 
I have tried many times, but it still can't be exact

![image](https://github.com/jshmrtn/vue3-gettext/assets/38585889/efbe3d5c-046d-45b0-913f-80c0c8509b03)
![image](https://github.com/jshmrtn/vue3-gettext/assets/38585889/719ee168-57c9-45cc-b4ba-3799d254b625)
![image](https://github.com/jshmrtn/vue3-gettext/assets/38585889/1062e5d7-5872-4133-b548-b1fd5cc45a04)
My config
![image](https://github.com/jshmrtn/vue3-gettext/assets/38585889/90870ee8-adcd-4fb6-b299-b8356ed26689)

Thanks

**Comment by huynamboz** [comment] 2024-06-26 17:19
i tried with ubuntu and it worked but window is not
![image](https://github.com/jshmrtn/vue3-gettext/assets/38585889/8ae80e3f-c56a-4152-9819-1837dd08e799)

**Comment by fjeddy** [comment] 2024-07-24 11:47
I got the same issue, it's been working fine until a recent update.

**Comment by fjeddy** [comment] 2024-08-18 17:38
I can't get this to work. The new version gives me

`vue-gettext-extract' is not recognized as an internal or external command, operable program or batch file.`

```js
module.exports = {

  input: {
    exclude: [
      './assets/images',
      './assets/locale',
      './assets/scss'
    ]
  },

  output: {
    locales: [
      'nb'
    ],
    path: './src/assets/locale',
    potPath: './locale.pot',
    jsonPath: '../../../public/locale',
    splitJson: true,
    flat: false,
    linguas: false
  }

}
```

**Comment by lzurbriggen** [comment] 2024-08-21 09:32
@fjeddy Sorry, I messed up the `bin` paths. Please try again with `4.0.0-alpha.6`

**Comment by fjeddy** [comment] 2024-08-21 09:51
It's running now, but it's not actually extracting anything, same result as before, empty files. It's also so fast, so incredibly fast, that it doesn't seem like it's actually parsing any files. It spits out a response just as fast as I hit enter on the command.

gettext.config.cjs
```js
module.exports = {

  input: {
    exclude: [
      './assets/images',
      './assets/locale',
      './assets/scss'
    ]
  },

  output: {
    locales: [
      'nb'
    ],
    path: './src/assets/locale',
    potPath: './locale.pot',
    jsonPath: '../../../public/locale',
    splitJson: true,
    flat: false,
    linguas: false
  }

}
```

output
```
Input directory: ./src
Output directory: ./src/assets/locale
Output POT file: src\assets\locale\locale.pot
Locales: nb

Searching: src\**\*.js
Searching: src\**\*.ts
Searching: src\**\*.vue
Excluding: src\assets\images
Excluding: src\assets\locale
Excluding: src\assets\scss


Extraction successful, src\assets\locale\locale.pot created.
Merged: src\assets\locale\nb\app.po
```

**Comment by lzurbriggen** [comment] 2024-08-21 11:47
@fjeddy I managed to reproduce this and pushed a fix with [v4.0.0-alpha.7](https://github.com/jshmrtn/vue3-gettext/releases/tag/v4.0.0-alpha.7), please let me know if it works!

**Comment by fjeddy** [comment] 2024-08-21 12:13
Nice, everything seems to be working fine now!

As a sidenote, before it would spit out how many strings it found and it's now spitting out a list of all the files it searched through, spamming the console a bit. Is the removal of the "summary" that was there in 2.4.0 on purpose?

**Comment by lzurbriggen** [comment] 2024-08-21 12:31
@fjeddy Nice!

> Is the removal of the "summary" that was there in 2.4.0 on purpose?

Iirc that was a feature of https://github.com/lukasgeiter/gettext-extractor that I now replaced with a custom parser and would have to implement myself. Probably a good idea, thanks for the input.

**Closed by lzurbriggen** 2024-08-21 12:31 UTC
Labels: bug

**Comment by huynamboz** [comment] 2024-08-21 12:58
Newest version worked for me, thanks @lzurbriggen ❤️
